
shp_settings_copy.post_settings_form:
  path: '/admin/config/shp_settings_copy/postsettings'
  defaults:
    _form: '\Drupal\shp_settings_copy\Form\PostSettingsForm'
    _title: 'PostSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

