<?php

/**
 * @file
 * Contains views_calculated_date.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_calculated_date_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_calculated_date module.
    case 'help.page.views_calculated_date':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add a calculated argument for datetime fields for views.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function views_calculated_date_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_field_views_data_alter().
 */
function views_calculated_date_field_views_data_alter(array &$data, \Drupal\field\FieldStorageConfigInterface $field_storage) {
  if ($field_storage->get('type') === 'datetime') {
    foreach ($data as $table_name => $table_data) {
      // Get the group name.
      $group = $data[$table_name][$field_storage->getName() . '_value']['group'];

      // Use these values for the type and help text.
      $argument_type = 'calculated';
      $help_text = t('Calculated Date.');

      // Create the calculated arguments.
      $data[$table_name][$field_storage->getName() . '_value_' . $argument_type] = [
        'title' => $field_storage->getLabel() . ' (' . $argument_type . ')',
        'help' => $help_text,
        'argument' => [
          'field' => $field_storage->getName() . '_value',
          'id' => 'datetime_' . $argument_type,
          'entity_type' => $field_storage->get('entity_type'),
          'field_name' => $field_storage->getName(),
        ],
        'group' => $group,
      ];
    }
  }
}
