<?php

/**
 * @file
 *   Contains the dc.module file for the Destination Central module.
 */
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Denotes that the entity content is newly imported from Afar.
 */
const DC_AFAR_STATUS_NEW = 1;

/**
 * Denotes that the entity content is freshly updated from Afar.
 */
const DC_AFAR_STATUS_REVISED = 2;

/**
 * Implements hook_help().
 */
function dc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dc module.
    case 'help.page.dc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a bundle-able Destination Central content entity used to store Destination Central content.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_operation()
 */
function dc_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'dc_content') {
    return [];
  }

  $operations = [];
  /** @var \Drupal\Core\Field\FieldItemListInterface $status_field */
  $status_field = $entity->status;
  $access_result = $status_field->access('update', NULL, TRUE);
  if ($access_result->isAllowed()) {
    $operations['publish'] = [
      'title' => $status_field->value ? t('Unpublish') : t('Publish'),
      'url' => $entity->urlInfo('toggle-status'),
    ];
  }

  return $operations;
}

/**
 * Implements hook_theme().
 */
function dc_theme($existing, $type, $theme, $path) {
  return [
    'dc_afar_status' => [
      'variables' => [
        'value' => NULL,
        'text' => NULL,
        'class' => NULL,
      ],
      'template' => 'dc-afar-status',
    ],
  ];
}
