language.entity.*:
#language.entity.*.third_party.shp_tilepage:
#  type: mapping
  type: config_entity
  label: 'Extra Language Field'
  mapping: 
    polarCountryCode:
      type: string
      label: 'Country Code'
    countryName:
      type: string
      label: 'Country Name'
    availableCurrency:
      type: string
      label: 'Region Currency'
    region:
      type: string
      label: 'Region Name'
    regionShort:
      type: string
      label: 'Region Short'
    langType:
      type: string
      label: 'Entry Type'



