<?php

/**
 * @file
 * Contains collection.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function collection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the collection module.
    case 'help.page.collection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a bundle-able collection entity used to store collections of data.') . '</p>';
      return $output;

    default:
  }
}
