api: 2

core: 8.x

projects:
  drupal:
    version: 8.6.x
    patch:
      text-processed-fix: https://www.drupal.org/files/issues/2018-05-15/text-processed-fix.patch
  key_value: 1.x
  key: 1.x
  encrypt: 3.x
  conflict:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: "https://github.com/drupaldeploy/drupal-conflict.git"
  multiversion:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: "https://github.com/dickolsson/drupal-multiversion.git"
  replication:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: "https://github.com/relaxedws/drupal-replication.git"
  workspace:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: "https://github.com/timmillwood/drupal-workspace.git"
