<?php

/**
 * @file
 * Contains shp_settings_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shp_settings_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shp_settings_rest module.
    case 'help.page.shp_settings_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send config settings via REST') . '</p>';
      return $output;

    default:
  }
}

/*

To-Do.

Permissions

*/