module:
  admin_toolbar: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  config: 0
  config_filter: 0
  conflict: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  deploy: 0
  deploy_individual: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  field: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  image: 0
  key_value: 0
  kint: 0
  link: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  multiversion: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  queue_ui: 0
  quickedit: 0
  relaxed: 0
  remote_image: 0
  replication: 0
  rest: 0
  restui: 0
  serialization: 0
  shp_settings_copy: 0
  simpletest: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  workspace: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
