dc_annotate.settings:
  type: config_object
  label: 'DC annotate settings'
  mapping:
    afar:
      type: mapping
      label: 'Afar settings'
      mapping:
        address:
          type: string
          label: 'Afar mail address'
        from:
          type: string
          label: 'Afar from mail address'
        cc:
          type: string
          label: 'Afar cc mail addresses'
        bcc:
          type: string
          label: 'Afar bcc mail addresses'
        subject:
          type: string
          label: 'Afar mail subject'
        body:
          type: string
          label: 'Afar mail body'
