<?php

/**
 * @file
 * Main module file for dc_annotate.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\dc\Entity\DCContent;

/**
 * Implements hook_form_alter().
 */
function dc_annotate_form_alter(array &$form, FormStateInterface $form_state) {
  if ($form['#form_id'] === 'comment_dc_edit_request_form') {
    $alter_object = new \Drupal\dc_annotate\Form\DcEditRequestFormatAlter();
    $alter_object->alter($form, $form_state);
  }

}

/**
 * Implements hook_mail().
 */
function dc_annotate_mail($key, &$message, $params) {
  switch ($key) {

    case 'afar_edit_request';
      $mail = new \Drupal\dc_annotate\AfarEditRequestMail(\Drupal::service('dc_annotate.token'), \Drupal::config('dc_annotate.settings'));
      $mail->mail($message, $params);
      break;

    default:
      throw new \InvalidArgumentException('Non valid mail key');

  }
}


/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function dc_annotate_dc_content_presave(DCContent $entity) {

  // Set afar_status to new upon create.
  if ($entity->isNew()) {
    $entity->set('afar_status', DC_AFAR_STATUS_NEW);
  }
  // Unset afar_status upon publish/unpublish.
  else {
    $published_changed = $entity->get('status')[0]->value != $entity->original->get('status')[0]->value;
    if ($published_changed) {
      $entity->set('afar_status', NULL);
    }
  }

}
